# Generated by Django 5.0.2 on 2024-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(default='profiledefault.png', upload_to='uploads/product/'),
        ),
    ]
