# Generated by Django 5.0.2 on 2024-03-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_profile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
