# Generated by Django 5.0.2 on 2024-03-31 15:47

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_profile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(blank=True, default=Store.models.get_default_image, null=True, upload_to=''),
        ),
    ]
